[package]
name = "deadlocked"
version = "1.2.0"
edition = "2024"

[dependencies]
shared.workspace = true
utils.workspace = true

glam.workspace = true
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
uuid.workspace = true

bytemuck = "1.24"
egui = "0.36"
egui_glow = { version = "0.36", features = ["winit"] }
egui-winit = { version = "0.36", default-features = false, features = [
    "clipboard",
    "links",
    "x11",
] }
epaint = { version = "0.36", features = ["serde"] }
glutin = { version = "0.32", default-features = false, features = [
    "x11",
    "egl",
] }
glutin-winit = { version = "0.5", default-features = false, features = [
    "x11",
    "egl",
] }
nix = { version = "0.31", features = ["ioctl"] }
rand = "0.10"
rand_distr = "0.6"
semver = "1.0"
toml = "1.0"
ureq = { version = "3", features = ["json"] }
winit = { version = "0.30", default-features = false, features = ["x11"] }

[features]
read-only = []
